sudo: required
services: 
  - docker

before_install:
  - docker build -t gniwll/docker-react -f Dockerfile.dev .

script: 
  - docker run gniwll/docker-react npm run test -- --coverage

deploy: 
  provider: heroku
  api_key: "$HEROKU_API_KEY"
  on: 
    branch: master